FROM andy67/custom:python-base3.12-slim

# Install required system packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements first to leverage Docker cache
COPY requirements.txt .
RUN uv pip install --system --no-cache-dir -r requirements.txt


CMD ["python", "/app/manager/manager.py"] 