FROM andy67/custom:python-base3.12-slim

# Install required system packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements first to leverage Docker cache
COPY requirements.txt .
COPY docker-entrypoint.sh /usr/local/bin/

# Make entrypoint script executable
RUN chmod +x /usr/local/bin/docker-entrypoint.sh


RUN uv pip install --system --no-cache-dir -r requirements.txt


# Set PYTHONPATH to include /app
ENV PYTHONPATH=/app

ENTRYPOINT ["docker-entrypoint.sh"]
# CMD ["python", "/app/normalizer/main.py"]
# Alternative to keep container running indefinitely:
CMD ["tail", "-f", "/dev/null"] 